name: Pack Mod
on:
  push:
    branches: [main]
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Switch to the workspace
        run: cd ${{ github.workspace }}
      - name: Zip up the mod
        run: zip community_decorations.zip * */* */*/* -x *.sh
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: community-decorations
          path: ${{ github.workspace }}/community_decorations.zip

